# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ""
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, "README.rst")
if os.path.exists(readme_path):
    with open(readme_path, "rb") as stream:
        readme = stream.read().decode("utf8")


setup(
    long_description=readme,
    name="sayn",
    version="0.4.0",
    description="Data-modelling and processing framework for automating Python and SQL tasks",
    python_requires="==3.*,>=3.6.0",
    project_urls={
        "homepage": "https://173tech.github.io/sayn",
        "repository": "https://github.com/173TECH/sayn",
    },
    author="Robin Watteaux",
    author_email="robin@173tech.com",
    maintainer="Adrian Macias",
    maintainer_email="adrian@173tech.com",
    license="Apache-2.0",
    entry_points={"console_scripts": ["sayn = sayn.cli:cli"]},
    packages=[
        "sayn",
        "sayn.core",
        "sayn.database",
        "sayn.logging",
        "sayn.scaffolding",
        "sayn.scaffolding.data.init_project.python",
        "sayn.tasks",
        "sayn.utils",
    ],
    package_dir={"": "."},
    package_data={
        "sayn.scaffolding": [
            "data/init_project/*.md",
            "data/init_project/*.txt",
            "data/init_project/*.yaml",
            "data/init_project/dags/*.yaml",
            "data/init_project/sql/*.sql",
        ]
    },
    install_requires=[
        "click==7.*,>=7.0.0",
        "colorama==0.*,>=0.4.3",
        "halo==0.*,>=0.0.30",
        "jinja2==2.*,>=2.10.3",
        "pydantic==1.*,>=1.6.1",
        "ruamel.yaml==0.*,>=0.16.12",
        "sqlalchemy==1.*,>=1.3.12",
    ],
    extras_require={
        "all": [
            "graphviz==0.*,>=0.14.0",
            "psycopg2==2.*,>=2.8.5",
            "pymysql==0.*,>=0.9.3",
            "snowflake-connector-python==2.*,>=2.0.3",
            "snowflake-sqlalchemy==1.*,>=1.1.18",
        ],
        "dev": [
            "black==19.*,>=19.10.0.b0",
            "flake8==3.*,>=3.8.3",
            "mkdocs==1.*,>=1.1.2",
            "mkdocs-material==6.*,>=6.0.2",
            "mkdocstrings==0.*,>=0.13.6",
            "pytest==5.*,>=5.4.3",
            "pytest-sugar==0.*,>=0.9.3",
        ],
        "graphviz": ["graphviz==0.*,>=0.14.0"],
        "mysql": ["pymysql==0.*,>=0.9.3"],
        "postgresql": ["psycopg2==2.*,>=2.8.5"],
        "snowflake": [
            "snowflake-connector-python==2.*,>=2.0.3",
            "snowflake-sqlalchemy==1.*,>=1.1.18",
        ],
    },
)
