name: CI
on: pull_request
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files

  Tests:
    needs: Linting
    runs-on: ubuntu-latest
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [Ubuntu]
        python: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade setuptools
        run: pip install --upgrade setuptools
      - name: Install Poetry
        run: pip install poetry
      - name: Install packages
        run: poetry install
      - name: Run tests
        run: pytest

